# Generated by Django 5.0.1 on 2024-01-10 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=10)),
                ('department_number', models.CharField(max_length=10)),
                ('commune', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('main_house', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specie', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('for_adoption', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
                ('posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('avatar', models.CharField(default='https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('houses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('pets', models.ManyToManyField(to='api.pet')),
                ('posts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
