# Generated by Django 5.0.1 on 2024-01-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='houses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
