# Generated by Django 5.0.1 on 2024-01-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_houses_remove_user_pets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='petPhoto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pet'),
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.AlterField(
            model_name='address',
            name='homeOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.user'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ManyToManyField(related_name='pets', to='api.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.user'),
        ),
    ]
