# Generated by Django 5.0.1 on 2024-01-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_pet_photos_remove_pet_posts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='homeOwner',
            new_name='home_owner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='petPhoto',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postedBy',
        ),
        migrations.AddField(
            model_name='photo',
            name='pet_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_photos', to='api.pet'),
        ),
        migrations.AddField(
            model_name='photo',
            name='post_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_photos', to='api.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='pet_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_pets', to='api.pet'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_users', to='api.user'),
        ),
    ]
