# Generated by Django 4.2.7 on 2023-11-10 02:01

import data.extensions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=data.extensions.get_uuid, max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('building_number', models.CharField(max_length=250)),
                ('department_number', models.CharField(max_length=250)),
                ('commune', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('has_backyard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owners_pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=data.extensions.get_uuid, max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('specie', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=250)),
                ('need_backyard', models.BooleanField(default=False)),
                ('for_adoption', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=data.extensions.get_uuid, max_length=250)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=data.extensions.get_uuid, max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=250)),
                ('houses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.address')),
                ('pets', models.ManyToManyField(through='data.Owners_pets', to='data.pet')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.post')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.photo'),
        ),
        migrations.AddField(
            model_name='pet',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.post'),
        ),
        migrations.AddField(
            model_name='owners_pets',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pet'),
        ),
        migrations.AddField(
            model_name='owners_pets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
    ]
