"""empty message

Revision ID: 80ff3b747ee1
Revises: 5524f919f082
Create Date: 2024-03-22 22:31:35.636930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ff3b747ee1'
down_revision = '5524f919f082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_residence', sa.Boolean(), nullable=True))

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_adoption_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_location', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('actual_location')
        batch_op.drop_column('last_adoption_date')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('main_residence')

    # ### end Alembic commands ###
