"""empty message

Revision ID: b395f8f42a3c
Revises: ef0c832a5693
Create Date: 2024-03-17 23:12:33.479813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b395f8f42a3c'
down_revision = 'ef0c832a5693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
