"""empty message

Revision ID: bba4bd64aeca
Revises: a5abedb6a772
Create Date: 2024-03-11 23:32:45.315313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba4bd64aeca'
down_revision = 'a5abedb6a772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('addresses_owner_id_fkey', type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint('photos_pet_id_fkey', type_='foreignkey')
        batch_op.drop_column('pet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('photos_pet_id_fkey', 'pets', ['pet_id'], ['id'])

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('addresses_owner_id_fkey', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###
