"""empty message

Revision ID: e7a6397cc025
Revises: 80ff3b747ee1
Create Date: 2024-03-23 19:27:36.945610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a6397cc025'
down_revision = '80ff3b747ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_location', sa.Integer(), nullable=True))
        batch_op.drop_column('actual_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_location', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('current_location')

    # ### end Alembic commands ###
