"""empty message

Revision ID: ef0c832a5693
Revises: 4e8395ba8920
Create Date: 2024-03-17 22:24:21.734337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0c832a5693'
down_revision = '4e8395ba8920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('reference_post_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('reference_post_id',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
